; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "J Study Checker"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "정재욱"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\J-Study-Checker.exe"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "C:\Users\kimso\Downloads\app_icon.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$PROGRAMFILES\J-Study-Checker\J-Study-Checker.exe"
!insertmacro MUI_PAGE_FINISH

; Language files
!insertmacro MUI_LANGUAGE "Korean"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "J Study Checker Installer.exe"
InstallDir "$PROGRAMFILES\J Study Checker"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show

Section "MainSection" SEC01
  SetOutPath "$PROGRAMFILES\J-Study-Checker"
  SetOverwrite ifnewer
  File "C:\Users\kimso\Downloads\J-Study-Checker\J-Study-Checker.exe"
  CreateDirectory "$SMPROGRAMS\J Study Checker"
  CreateShortCut "$SMPROGRAMS\J Study Checker\J Study Checker.lnk" "$PROGRAMFILES\J-Study-Checker\J-Study-Checker.exe"
  CreateShortCut "$DESKTOP\J Study Checker.lnk" "$PROGRAMFILES\J-Study-Checker\J-Study-Checker.exe"
  SetOutPath "$LOCALAPPDATA\J-Study-Checker\Datas"
  SetOverwrite try
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Datas\user_list.bin"
  SetOutPath "$LOCALAPPDATA\J-Study-Checker\Fonts\NanumGothic"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Fonts\NanumGothic\NanumGothic.otf"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Fonts\NanumGothic\NanumGothic.ttf"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Fonts\NanumGothic\NanumGothicBold.otf"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Fonts\NanumGothic\NanumGothicBold.ttf"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Fonts\NanumGothic\NanumGothicExtraBold.otf"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Fonts\NanumGothic\NanumGothicExtraBold.ttf"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Fonts\NanumGothic\NanumGothicLight.otf"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Fonts\NanumGothic\NanumGothicLight.ttf"
  SetOutPath "$LOCALAPPDATA\J-Study-Checker\Images\Backgrounds"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Backgrounds\analysis_grades_background.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Backgrounds\analysis_study_background.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Backgrounds\calculator_background.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Backgrounds\home_background.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Backgrounds\login_background.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Backgrounds\notification_background.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Backgrounds\register_background.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Backgrounds\reminder_background.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Backgrounds\stopwatch_background.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Backgrounds\study_background.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Backgrounds\study_calendar_background.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Backgrounds\timer_background.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Backgrounds\time_table_background.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Backgrounds\user_background.png"
  SetOutPath "$LOCALAPPDATA\J-Study-Checker\Images\Icons"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Icons\app_icon.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Icons\custom_timer_button_1.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Icons\custom_timer_button_2.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Icons\five_minutes_timer_button_1.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Icons\five_minutes_timer_button_2.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Icons\notification_icon_1.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Icons\notification_icon_2.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Icons\one_minute_timer_button_1.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Icons\one_minute_timer_button_2.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Icons\ten_minutes_timer_button_1.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Icons\ten_minutes_timer_button_2.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Icons\user_icon_1.png"
  File "C:\Users\kimso\OneDrive\문서\J-Study-Checker\Images\Icons\user_icon_2.png"
SectionEnd

Section -Post
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$PROGRAMFILES\J-Study-Checker\J-Study-Checker.exe"
SectionEnd