name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install
        run: |
          pip install pyinstaller
          pip install sortedcontainers


      - name: Build
        run: |
          pyinstaller --onefile --windowed --paths SourceCodes --hidden-import sortedcontainers --add-data "Images;Images" --add-data "Datas;Datas" --add-data "Fonts;Fonts" SourceCodes/app.py


      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: J-Study-Checker
          path: dist/*

